numpy 라이브러리 시작하기

제곱근 출력

numpy의 별명은 np

파이값 np.pi , 삼각함수 np.sin, np.con 출력 

rand()함수 실행하여 n개의 실수를 랜덤하게 생성 = random 라이브러리의 randint() 함수의 실수 (real number) 버전 

choice(6,10) : 0~5 까지 10번 랜덤하게 출력 

choice(6,10,replace=False) : 0~5까지 10번 중복없이 랜덤하게 출력 

choice(6,10,p=[0.1,0.2,0.3,0.2,0.1,0.1]) : p확률 만큼 0~5까지 10번 랜덤하게 출력 

In [1]:
import numpy
print(numpy.sqrt(2))
# 2의 제곱근을 출력

1.4142135623730951


In [2]:
import numpy as np # numpy의 별병은 np
print(np.sqrt(2))

1.4142135623730951


In [7]:
import numpy as np 
print(np.pi) # 파이 값
print(np.sin(0)) # 삼각함수 
print(np.cos(np.pi)) # 삼각함수 

3.141592653589793
0.0
-1.0


In [11]:
import numpy as np
a=np.random.rand(5) # rand() 함수를 실행하면 0~1 사이에 있는 5개의 실수가 랜덤하게 생성
print(a)
print(type(a))
# 리스트와 비슷하게 생긴 numpy.ndarray 타입의 데이터가 생성 
# nd? N-Dimensional, N 차원 array? 배열 
# random 라이브러리의 randint() 함수의 실수(real number) 버전 

[0.25508245 0.21816205 0.85718297 0.85477226 0.09124642]
<class 'numpy.ndarray'>


In [13]:
import numpy as np
print(np.random.choice(6,10)) 
# 0~5 사이의 숫자를 랜덤하게 10번 선택 

[3 0 3 3 4 4 3 4 2 3]


In [17]:
import numpy as np
print(np.random.choice(10,6,replace=False))
# 만약 한 번 뽑은 숫자를 다시 뽑지 못하게 하고 싶다면 replace=False 설정 
# 0~9 사이의 숫자를 중복 없이 6번 선택 

[9 2 0 4 6 5]


In [21]:
import numpy as np
print(np.random.choice(6,10, p=[0.1,0.2,0.3,0.2,0.1,0.1]))

[1 2 4 2 1 2 5 4 1 0]
